juju/testing

- filetesting/filetesting.go
These won't work on windows for now.
> Skipping chmod checks for now

- LICENCE
(Review request: http://reviews.vapour.ws/r/1275/)
> lp1435974 - Modify LICENSE to include copyright (juju/testing)

- LICENCE
(Review request: http://reviews.vapour.ws/r/1272/)
> lp1435974 - Modify LICENSE to include copyright (juju/testing 1.22)

- LICENCE
(Review request: http://reviews.vapour.ws/r/1312/)
> LGPL v3 License (juju/testing master)

- LICENCE
(Review request: http://reviews.vapour.ws/r/1310/)
> LGPL v3 License (juju/testing 1.22)

- LICENCE
(Review request: http://reviews.vapour.ws/r/1345/)
> LGPL v3 License (juju/testing 1.23)

- mgo.go
We were about to duplicate it for the third time in a third project.
(Review request: http://reviews.vapour.ws/r/1426/)
> add IsolatedMgoSuite

- httptesting/http.go
- httptesting/http_test.go
We allow a body to be specified as a Go value, a common requirement.
(Review request: http://reviews.vapour.ws/r/1442/)
> support JSONBody

- httptesting/http.go
- httptesting/http_test.go
This allows us to put a seekable body into AssertJSONCall and
later retrieve it for use with custom Do methods that require
a seekable reader.
(Review request: http://reviews.vapour.ws/r/1448/)
> httptesting: maintain seekerness of body

- httptesting/http.go
- httptesting/http_test.go
The earlier change to avoid wrapping seekers conflicted with
the http NewRequest logic.
(Review request: http://reviews.vapour.ws/r/1458/)
> httptesting: infer ContentLength correctly

- stub.go
- stub_test.go
The Stub type was not thread safe, yet could easily be used in a
multithreaded environment. We see this in LP 1459064.
To address this all the public fields in Stub have been made private
and either accessors which return a _copy_ of the values, ie stub.Calls,
or checkers which assert the internal contents match a supplied list, have
been added.
Additionally, unused features like Stub.DefaultError have been removed. I
could not find a usage of that inside Juju -- the value of DefaultError
was always nil.
(Review request: http://reviews.vapour.ws/r/1813/)
> Refactor testing/stub.go

- httptesting/http.go
- httptesting/http_test.go
(Review request: http://reviews.vapour.ws/r/2661/)
> Add ExpectHeader on JSONCallParam.

- httptesting/http.go
This provides a closer link to the underlying HTTP mechanism.
We don't change DoRequest itself because we have hundreds
of uses of that in other packages.
(Review request: http://reviews.vapour.ws/r/2781/)
> httptesting: add Do function to allow us to get the actual HTTP response

- httptesting/http.go
- httptesting/http_test.go
Add a request rewriting RoundTripper to httptesting.
(Review request: http://reviews.vapour.ws/r/2825/)
> Add Transport to httptesting

- checkers/codec.go
- checkers/codec_test.go
(Review request: http://reviews.vapour.ws/r/2873/)
> Switch to using gopkg.in/yaml.v2

- filetesting/stub.go
StubFile implements most of the methods of os.FIle.
(Review request: http://reviews.vapour.ws/r/3503/)
> Add a stub file type.

- home.go
JujuHomePath helper is introduced to clean up many tests
composing the juju home path by hand.
(Review request: http://reviews.vapour.ws/r/3581/)
> Added JujuHomePath helper

- home.go
This is necessary for a still unmerged change.
(Review request: http://reviews.vapour.ws/r/3671/)
> Updated JUJU_HOME (now JUJU_DATA)

- home.go
(Review request: http://reviews.vapour.ws/r/3723/)
> Renamed juju data path again

- cleanup.go
- cmd.go
Also remove unnecessary uncommented types.
(Review request: http://reviews.vapour.ws/r/4416/)
> testing: remove deprecated AddSuiteCleanup function

- cmd.go
- cmd_test.go
This PR adds a new type, PatchExecHelper that makes it easy to patch out a call to exec.Command so that you can mock out calls to external commands without having to resort to nasty bash/batch scripts, and is much more flexible than the existing PatchExecutable that exists in the same file (which has limited usefulness on Windows, and assumes you're patching out a call to something in the path, and currently only lets you test the args *or* the output. 
PatchExecHelper lets you configure stderr, stdout, the exit code, and gives you a way to verify the arguments that were passed to exec.Command.... all wrapped up in one type you embed and one method you call.
CaptureOutput runs a function, and captures all data written to os.Stderr and os.Stdout. This is very useful for testing CLI code …
> add PatchExecHelper and CaptureOutput helpers

- home.go
- home_test.go
We have been ignoring the error return. :(
(Review request: http://reviews.vapour.ws/r/4753/)
> Handle the error return from utils.SetHome().

- mgo.go
Fixes LP 1589353
(Review request: http://reviews.vapour.ws/r/4984/)
> testing: don't panic during TearDownTest if SetUpTest failed

- mgo.go
Mongo 2.4 is faster with --nojournal, but 3.2 is much slower with
it (see https://jira.mongodb.org/browse/SERVER-21198). Check "mongod
--version" to decide whether to pass --nojournal when starting the
server.
This only detects the version the first time the server is started in a
test run and caches it after that.
(Review request: http://reviews.vapour.ws/r/5084/)
> Detect mongod version before starting test server

- clock.go
(Review request: http://reviews.vapour.ws/r/5216/)
> copy clock from juju/juju/testing

- checkers/log.go
- checkers/log_test.go
- log.go
- log_test.go
Minor changes to deal with changes in the loggo functions.
(Review request: http://reviews.vapour.ws/r/5350/)
> Update to use the latest loggo.

- mgo.go
Enabling logging/debugging in mgo adds
a significant amount of overhead to Juju
tests. For example, on my laptop the
state package tests take ~100s longer
with these enabled.
https://bugs.launchpad.net/juju/+bug/1625768
> Disable mgo logging/debugging by default

- imports.go
parse into `srcDir` to enable `vendor` as highest priority import path
> enable vendor as the highest priority import path

- constants.go
Bring into the main testing repository from the juju repo.
> Add short and long timeouts.

- mgo.go
Some juju test suites overwrite HOME env var which is required to use the juju-db snap.
Follow up to #148
> Fix issue with juju suites overwriting HOME

- checkers/deepequal.go
- checkers/flags_1_12.go
- checkers/flags_1_13.go
- checkers/flags_1_14.go
- checkers/multichecker.go
- checkers/multichecker_test.go
- AddExpr takes a go expression with _ being the wildcard.
- Slight refactor of multi checker.
- Fix bug with unexported fields and unexported embeds.
> Add go style expressions for multichecker matching.

- go.mod
- go.sum
- mgo.go
collstats appears to be quite a slow way to determine if the collection is capped.
> Fix performance issue with using collstats.

- mgo.go
Only add mmap storage engine args if we are using that storage engine
> Only use mmapv1 args for mmap storage engine

- mgo.go
Mongo 3 (which is still used on Windows right now) doesn't like the maxTransactionLockRequestTimeoutMillis server parameter.
So only pass it for v4 or greater.
> Only use maxTransactionLockRequestTimeoutMillis for mongo 4
