juju/testing

fake.go
fake_test.go

Fake (and its components) was developed during work on the GCE provider.  I expect it has broader usefulness, so I'm proposing it here.

Add a base "fake" type, for using in testing.

---

osenv.go
osenv_test.go

Treat envvars as case insenstive when whitelisting in OsEnvSuite
Because windows envvars are case insensitive but case preserving, it's possible to have a valid common value, like PATH, which would be accepted by the OS, get scrubbed. This branch changes the whitelisting to use lower cased comparisons on windows.

Make preservation of envvars case insensitive on windows

---

cmd.go

Now can have multiple calls to an echo-args patched command and record all outputs. Can also supply optional exit codes so you can emulate a sequence of calls, some failing, some executing OK.

Multiple echo-args calls

---

httptesting/http.go
httptesting/http_test.go

If AssertJSONRequest has an ExpectBody that is of type BodyAsserter then this will be called to check the response.

Accept a function for ExpectBody to allow custom body checking.

---

stub.go
stub_test.go

Correct two licence headers from AGPL to LGPL as noted by ubuntu release review:
https://bugs.launchpad.net/juju-core/+bug/1442132
(Review request: http://reviews.vapour.ws/r/1415/)

Correct licence header in stub.go and stub_test.go to LGPLv3

---

log.go

Currently when testing a juju command that uses cmd.Log, the
logging test output is suppressed because the logging setup
changes the default writer. This PR changes things so that
the test logger uses a different writer so we can still see
debugging log messages in such tests.
(Review request: http://reviews.vapour.ws/r/1724/)

testing: do not use default writer in LoggingSuite

---

cmd.go
cmd_test.go
mgo.go

Strings were generated with 2 sets of quotes in tests. This patch resolve this problem.
There is a difference between "%q" in bash and "%q" in Go. In bash "%q" will print the associated argument shell-quoted and in Go "%q" will print the associated argument double-quoted.  
For example:
```printf "%q" "hello world"``` will print ```hello\ world```
```fmt.Printf("%q", "hello world")``` will print ```"hello world"```
ShQuote quotes the string so no metacharacters within string will be interpreted as such.
Also, I added two more paths for mongod. These are needed in tests where PATH is being completely removed and to get the unit tests going on CentOS

Various test fix on CentOS

---

cmd.go

Pretty much what the title says
(Review request: http://reviews.vapour.ws/r/2558/)

fix1491398: Make windows batch quoting conformant with unix one

---

httptesting/http.go
httptesting/http_test.go

This allows AssertJSONCall and DoRequest to be used with externally
defined services. The change is backwardly compatible.
(Review request: http://reviews.vapour.ws/r/2778/)

httptesting: allow hosted URLs

---

mgo_unix.go
mgo_windows.go
osenv.go
tcpproxy.go
tcpproxy_test.go

There are at least two places in juju-core that start a little
custom TCP proxy in order to be able to break a connection
deliberately.
This can be be used for those and is slightly more general to boot.

testing: add TCPProxy

---

stub.go
stub_test.go

Add convenience methods Stub.PopNoErr() and Stub.CheckNoCalls().  These methods help make intent more obvious and encourage a correct approach in a couple common cases.
(Review request: http://reviews.vapour.ws/r/3162/)

Add Stub.PopNoErr() and Stub.CheckNoCalls().

---

checkers/bool_test.go
norace.go
race.go

Some juju tests need to be skipped because they do not pass under
the race detector. To simplify this, add a constant so we can do:
if testing.RaceEnabled {
t.Skip("skipping package test under race detector, see LP NNNNN")
}
// normal gocheck stub
While I'm here, fix a test failure with testing/checkers under Go 1.4+
(Review request: http://reviews.vapour.ws/r/3202/)

testing: add constant to detect race detector

---

goversion12.go
goversion13.go
goversion14.go
goversion15.go

Add a constant that can be used to conditionally skip tests. eg.
if testing.GOVERSION == 1.5 {
t.Skip("skipping package, see LP NNN")
}
Additional note: GOVERSION is an untyped constant, not an IEEE floating
point value. It is safe to do comparisons on it like equals and greater
than/less than without concerns about precision.
(Review request: http://reviews.vapour.ws/r/3257/)

testing: add GOVERSION constant

---

checkers/bool_test.go
mgo.go

When dialling Mongo, return and assert err is nil instead of calling
MustDial, which panics.
(Review request: http://reviews.vapour.ws/r/3332/)

juju/testing: Don't panic on Mongo test setup

---

mgo.go
mgo_test.go

Remove MustDial, it was only called in one place where an error would be
more appropriate.
Reset now returns an error, rather than panicing.
(Review request: http://reviews.vapour.ws/r/4071/)

testing: cleanup MgoInstance

---

cleanup.go
cleanup_test.go
home_test.go

If you call AddCleanup from a Test that uses a non-pointer receiver, then the cleanup
will actually never be called, because the original suite is no longer around.
Also, make AddCleanup automatically act like AddSuiteCleanup if it is called while we aren't inside a Test context. That way thinks like PatchValue actually work like we think they do, rather than having them just not work at all.

Add a panic() if AddCleanup is unsafe.

---

httptesting/http.go

The httptest.ResponseRecorder type has become more
sophisticated, and our code was being a bit devious
by constructing one without using the expected methods.
Fix by using the expected methods to make the ResponseRecorder.
We should eventually remove our use of ResponseRecorder entirely
and fix all the code that uses httptesting, but we don't
need to bite that bullet quite yet.
(Review request: http://reviews.vapour.ws/r/4317/)

httptesting: fix for Go 1.6

---

cmd.go

Preserve the existing environment variables on
Windows, or badness happens.
Fixes https://bugs.launchpad.net/bugs/1575463
(Review request: http://reviews.vapour.ws/r/4718/)

Fix PatchExecHelper.GetExecCommand on Windows

---

tcpproxy.go
tcpproxy_test.go

This will allow us to break individual mongodb connections while
allowing the session to recover.
(Review request: http://reviews.vapour.ws/r/4797/)

testing: add TCPProxy.CloseConns

---

mgo.go

This panic fires frequently in out webscale mongodb CI environment. 
Stop panicing as we can easily return the error.
(Review request: http://reviews.vapour.ws/r/4858/)

mgo: don't panic while resetting admin password

---

cleanup.go
mgo.go

In Mongo 3.2 creating collections and indexes and dropping databases is ~100x slower. Rather than requiring tests to recreate all of the collections and indexes for each test, clear out the data from all collections between tests.
Part of fixing LP-1573294: https://bugs.launchpad.net/juju-core/+bug/1573294
(And related Mongo bug: https://jira.mongodb.org/browse/SERVER-21198)
Also, ensure that test/suite cleanup callbacks are only called once - there are some tests that call setup/teardown during the test (yuck), which meant that the cleanups were done multiple times.
(Review request: http://reviews.vapour.ws/r/4890/)

Don't drop and recreate the database between tests

---

checkers/codec.go

This checker matches the analogous JSONEquals and YAMLEquals checkers.
(Review request: http://reviews.vapour.ws/r/5067/)

Added BSONEquals checker

---

mgo.go

The old code was splitting on \n which meant that a \r character was
left on the version line on windows. Using a bufio.Scanner handles the
newlines in a cross-platform way.
(Review request: http://reviews.vapour.ws/r/5163/)

lp:1596045 handle CRLF in mongo version line

---

mgo.go

Very rarely, but frequently enough in our test runs, dialing mgo will fail with "unexpected message".
Wrap that call in a retry, and try five times. Hopefully this will be sufficient. A minimal delay is specified.
(Review request: http://reviews.vapour.ws/r/5608/)

Retry mgo dial if unexpected message.

---

mgo.go

Now the mgo logging is output through loggo to the "mgo" logger.
This means it is now available to be shown, but not shown by default.
To enable in other tests, they can (after logging is set up) set:
loggo.GetLogger("mgo").SetLogLevel(loggo.TRACE)
Also, when the mongo server is changed by either restarting, or other tests killing it, the teardown now reconnects the session, which avoids some of the "no reachable servers" errors we were seeing.

Hook up mgo logging and reconnect properly.

---

mgo.go
mgo_test.go

This makes it easier to test what happens when a mongo socket
connections break.

add NewProxiedSession

---

mgo.go

When mongo exits with an error we output 20 lines of it's output. This
bumps that up to 100 lines to provide more context as to why mongo
errored.

Bump mongo error output to 100 lines

---

clock.go
clock_test.go

Adds a WaitAdvance method which ensures that there is something in
clock.waiting before actually advancing the time. Addtionally cause
Advance to log a debug message if it Advances time when clock.waiting
is empty.
Refs: https://bugs.launchpad.net/juju/+bug/1607044
QA:
1) Run the unit tests and ensure they all pass.

Update testing.Clock to improve robustness

---

checkers/deepequal.go
checkers/deepequal_test.go

This means tests won't need to concern themselves too deeply
about the time zone used in times unmarshaled from databases
or the network.
We also change the printed message to print the time nicely
rather than printing the details of the unexported time fields.

checkers: ignore time zone in DeepEqual

---

mgo.go

...because of a change to the Boost libraries. Tested on Yakkity and Xenial (bug showed up in Yakkity).
See https://bugs.launchpad.net/ubuntu/+source/juju-mongodb3.2/+bug/1581284 for background.

MongoDB needs --key=value not --key value now 

---

mgo.go

replicaset tests seem not to have been passing for some time, and require these changes in mgo.go:
* Add version 3.2 to the mongod paths
* Reinstate MustDial() function

Fixes for replicaset

---

mock_example_test.go
mocker.go

This type is designed to easily and dynamically mock out calls to methods/functions so that tests can declare expected arguments and their return values without having to define custom functions for each test. In addition, calls and return-values are logged so that when tests fail it's easy to pinpoint why.

Introduces a type which can be used to mock calls

---

tcpproxy.go
tcpproxy_test.go

This allows servers that are not responding in a timely manner to be
simulated.

tcpproxy: add pause and resume to the stream

---

mgo.go

The line is specifically:
2017-02-22T12:51:41.107+0400 I NETWORK  [thread1] waiting for connections on port 9999
I don't know if we are ready to support all of mongo 3.4, but this allows me to run the test suite on Mac OS X when I have whatever Mongo I could install from homebrew. It seems a safe enough change.

Mongo 3.4 uses a different string to indicate it is ready for connections

---

cmd.go

The EchoQuotedArgsUnix script writes
a file to record the command line arguments
of the process. The script was using
the basename, which only works as
expected if the command is run in the
CWD set at the time of the AssertEchoArgs
call.
Instead of this, write to the location
of the script + ".out", and then read
from the same location in AssertEchoArgs
using os/exec.LookPath. We also introduce
ReadEchoArgs to fetch the value without
checking its contents.

Fix EchoQuotedArgsUnix/AssertEchoArgs

---

cmd.go

In the Windows echo-args script, we were
still using the relative path for .out and
.exitcodes files. Use %~f0 to get the full
path to the script.
Also, write the .exitcodes file to the
correct location, and remove the AddCleanup
calls (which were cleaning up temporary
files that will be removed by gocheck.)

Fix PatchExecutableAsEchoArgs on Windows

---

mgo.go

Previously, MongoDB 2.4 (from juju-mongodb) and the system installed
MongoDB (2.6) were preferred over MongoDB 3.2 (which is actually used
in production).
Cache the MongoDB path alongside the version. Previously there was a
small chance that the cached version would not match the mongod
version. This also avoids unnecessarily looking up the mongod path all
the time.

Prefer mongod 3.2 and improve mongod info caching

---

mgo.go

This makes the Juju tests significantly faster.
Make the storage engine configurable via the
$JUJU_MONGO_STORAGE_ENGINE environment variable.

Default mongo storage backend to mmapv1

---

mgo.go

Add a method to report whether an MgoInstance
has SSL enabled, so clients can decide how to
connect.

Add MgoInstance.SSLEnabled method

---

mgo.go

--sslOnNormalPorts is deprecated past Mongo 2.6
Use the new --sslMode arg instead.

Remove deprecated --sslOnNormalPorts arg to mongod

---

mgo.go

juju/mongo tests failed, which identified this typo

Fix typo in mongo command

---

stub.go
stub_test.go

All current methods on testing Stub assume that the order of calls matters.
However, there are situations where we only care about the fact that the calls where made, not in what order they were made. For example, intermittent failures in https://bugs.launchpad.net/juju/+bug/1742222 specifically occur because we expect the calls to have been made but the calls in asynchronous system can be made in any order.
This PR adds a method that allows to check that the expected calls where made, not when they were made.

Stub check calls without order.

---

mgo.go

When building mongod, mmapv1 is only enabled by
default for x86 and x86_64. Change the tests to
use wiredTiger on other architectures.

testing: default to mmapv1 only on x86(_64)

---

mgo.go

In Mongo 3.4 it now prevents you from doing this. It doesn't seem like
it would ever be a really good idea to do, as it would arguably break
your system. (if you really were part of a replicaset, you've now lost
your ability to track what changes have and haven't been applied.)
It was semi-ok in that we are resetting the database, but since the
replicaset would still potentially be running, we really don't want to
do this.
This was done for Launchpad [Bug 1749078](https://pad.lv/1749078)

Don't try to truncate the local replicaset oplog.

---

mgo.go

Rather than having other code search for a 'mongod' just so we can report a version, we've already done the version check, and we can just report it. That also avoids any chance of skew, where the mongod we decide to use isn't the one we find later.

Expose the version of Mongo that we are testing against.

---

mgo.go
tcpproxy.go

If we don't have this then trying to restart the MgoServer can and does fail on bionic inside an isolation suite.

Add the location of mongod in bionic to the list of places we look.

---

mgo.go
mgo_test.go

This adds a boolean that lets us specify that Mongod should be started with a replSet enabled.
We have historically disabled this, because it adds a fair bit of time to Mongod startup (running this test suite takes 3s vs 5s).
However, the test suite also was *failing* when it was enabled, because we were deleting collections that Mongo needs to have to operate correctly. (The surprising one was local.replicaset.minvalid.)
Digging into what collections are in 'config', and 'local', we really don't want to be deleting anything in there. So this skips those collections explicitly.
I ran the test suite with Mongo 3.6 and Mongo 4.0.5 on Bionic and used this patch:
```
diff --git a/mgo.go b/mgo.go
index 296bb52..14eaeaa 100644
--- a/mgo.go
+++ b/mgo.go
@@ -251,6 +251,7 @@ func (inst …
```

Enable Mongo with Replica Sets

---

mgo.go

Else just use mmapv1 so we don't have to worry about the slowdown of the
test suite.
I wasn't able to merge the previous change to juju proper, because it slows down the juju/state test suite too much. This allows us to keep the test suite at the fast option until we are ready to use server side transactions.

If using Replicaset use wiredTiger.

---

mgo.go

This commit adds `/snap/juju-db/current/bin/monogod` to the list of searched paths when looking for a `mongod` instance.

Add support for finding the juju-db snap when looking for mongod

---

httptesting/http.go

The following changes are required so we can test against the
status code along with the error of a http request.
Changing this allows us to work with go-1.12 where the changes to
the http(s) server when calling https using http now returns a 400
status code instead of malformed garbage.
See: https://go-review.googlesource.com/c/go/+/98447/

Allow testing of DoRequest against status code

---

httptesting/http.go

When attempting to contact HTTPS url using a HTTP endpoint, in
go version < 1.12 it would return with a malformed garbage error.
In go version >= 1.12 the error is no longer returned and instead
a status code of 400 is returned.
In order to handle this is the correct manor for both past and future
runtimes we should hide this fact and just get prior errors report
that a bad request was sent.

Malformed errors

---

mgo.go

At some point mongo's address in use error changed. This will fix retry on address in use error.

Fix address already in use detection.

---

mgo.go

Too many test packages in juju override HOME env var
so instead for juju-db we pull HOME from /etc/passwd.

Sidestep HOME env var for juju-db snap testing

---

checkers/bool.go
checkers/deepequal.go
checkers/multichecker.go
checkers/multichecker_test.go

MultiChecker allows you to perform a DeepEquals but have bespoke checkers based on path matching.
For example, this allows the value at "b" to be ignored.
```
a1 := map[string]string{"a": "a", "b": "b", "c": "c"}
a2 := map[string]string{"a": "a", "b": "bbbb", "c": "c"}
checker := jc.NewMultiChecker().Add(`["b"]`, jc.Ignore)
c.Check(a1, checker, a2)
```
This allows the second element to have the SameContents check applied, ignoring order of elements:
```
a1 := [][]string{{"a", "b", "c"}, {"c", "d", "e"}}
a2 := [][]string{{"a", "b", "c"}, {"e", "c", "d"}}
checker := jc.NewMultiChecker().Add("[1]", jc.SameContents, jc.ExpectedValue)
c.Check(a1, checker, a2)
```

Add multi-checker

---

mgo.go

Tests create namespaced (by UUID) capped collections for their logs.
These collections must be removed at teardown; otherwise, their number
will grow without any bound and cause sequential teardowns to take
longer and longer.

Ensure that the namespaced collections in the logs db are removed during teardown.

---

mgo.go

By allowing suites that use MgoSuite to skip cleanup during test tear down, JujuConnSuite tests can be optimised to reuse collections.

Allow suites that depend on MgoSuite to disable cleanup.

---

checkers/time.go
checkers/time_test.go

Added time checkers:
- After: obtained time is after the expected time.
- Before: obtained time is before the expected time.
- Almost: obtained time is at most 1s before or after the expected time.

Added time checkers After, Before and Almost

---

go.mod
go.sum
patch.go
patch_test.go

os.GetEnv doesn't distinguish between unset vars and vars set to the empty string. However, LookupEnv does. This means PatchEnvironment would leave behind env vars set to the empty string when they were previously unset
These env var would then be picked up by LookupEnv, which can cause unexpected errors.
Update dependencies as a drive-by
- Verify unit tests pass
- Verify juju unit testing suite passes as usual using this in place of juju/testing
- Also, write a test for some code which uses os.LookupEnv, branching based it's second return var, and performs some validation on the env var value. Perhaps you are wish to parse a boolean config option from your environment. 
Verify these tests fail when you PatchEnvironment with upstream. Then verify the pass with this iteration

[JUJU-2271] PatchEnvironment now correctly unsets env vars

---

checkers/checker.go

By using a slower algorithm, we can avoid requiring the slices to be hashable element types.

Allow SameContents to work with unhashable contents.

---

checkers/error.go
checkers/error_test.go

The following makes it easier to compare errors. Currently, if we attempt to use satisfies checker, we'll more than likely end up with a deprecation warning that `Is` prefix predicate variants from the errors package are being used.
The solution is to make a new checker that we can move to, which has the semantics that we want moving forward.
You can use it in the following manner:
```
err := errors.ConstError("foo")
c.Check(err, jc.ErrorIs, errors.ConstError("foo"))
```

error.Is testing checker
